config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new' 
  end

  root 'welcome#index'

  resources :posts do
    resources :likes
    resources :comments do
      resources :likes
    end
  end

  get 'myprofile', to: 'users#myprofile'

  get 'myfriends', to: 'users#myfriends'

  get 'search_friend', to: 'users#search'

  get 'friend_results', to: 'users#friend_results'

  get 'users/:user_id/friends',to: "users#friends",as: 'user_friends'

  get 'users/:user_id/mutual_friends',to: "users#mutual_friends",as: 'mutual_friends'

  get 'users/:user_id/pendingrequests',to: "users#pendingrequests",as: 'user_pending_request'
  
  get 'users/:user_id/receievedrequests',to: "users#receievedrequests",as: 'user_receieved_request'
  
  post 'users/accept_request/:user_id', to: "friendships#accept",as: 'accept_request'
  
  delete 'users/unfriend/:user_id',to:"friendships#unfriend",as: "user_unfriend"

  resources:users, only: [:show, :destroy] do
    resources:friendships
  end  




  



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one :userdetail, dependent: :destroy
  accepts_nested_attributes_for :userdetail, allow_destroy: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friend_sent , class_name: 'Friendship' ,
          foreign_key: 'sent_by_id',
          inverse_of: 'sent_by',dependent: :destroy
  has_many :friend_request ,class_name: 'Friendship',
          foreign_key: 'sent_to_id',
          inverse_of: 'sent_to',dependent: :destroy
  has_many :friends_a_to_b, -> {  Friendship.friends },
          through: :friend_sent,source: :sent_to
  has_many :friends_b_to_a, -> { Friendship.friends },
          through: :friend_request,source: :sent_by
  has_many :pending_requests, -> { Friendship.not_friends },
          through: :friend_sent, source: :sent_to
  has_many :received_requests, -> { Friendship.not_friends },
          through: :friend_request, source: :sent_by

  def all_friends
    (friends_a_to_b+friends_b_to_a).uniq
  end
  #for search features
  def self.search(searchstring)
    searchstring.strip!
    first=match('email',searchstring)
    second=match('first_name',searchstring)
    third=match('last_name',searchstring)
    result = (first+second+third).uniq
    result
  end

  def self.match(fieldname,searchstring)
    where("#{fieldname} like ?","%#{searchstring}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id==self.id }
  end

  def full_name
    # first_name+" "+last_name
    "#{first_name} #{last_name}"
  end

  def with_userdetail
    build_userdetail if userdetail.nil?
    self
  end

  # def self.test
  #   where(first_name: "Rahul")
  # end
  # scope :testing, -> { where(first_name: "Rahul") }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def myprofile
    @user = current_user
    @posts =@user.posts
  end

  def myfriends
    @friends = current_user.friends
  end

  def show
    # byebug
    @user = User.find(id=params[:id])
    # @posts = @user.posts

    # byebug

    #show the post where post.where(post_type: "everyone") or 
    #where(post_type: "friends" && if current_user is friend of this user)

    @posts = @user.posts.where(post_type: "public") #every one extracted

    #if current user is friend then 'friends' visibility should be extracted
    
    if @user.friends_b_to_a.where(id: current_user).present? or @user.friends_a_to_b.where(id: current_user).present?
      @posts += @user.posts.where(post_type: "friends")
    end

    # byebug



  end


  def search
    if params[:friend].present?
      # @friends = User.all
      @all_friends = User.search(params[:friend])
      @all_friends = current_user.except_current_user(@all_friends)
      @friends = @all_friends.first(5)
      
      # byebug
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  def friend_results #yet to complete, find a way to send the data from FE to BE
    @all_friends = params[:format]
  end

  # check
  def friends
    @user=User.find(params[:user_id])
    @friends=@user.all_friends
  end

  def mutual_friends
    # byebug
    @user=User.find(params[:user_id])
    @friends=@user.all_friends  #a => b,c ,d
    #b => a,c,d
    #c,d
    @my_friends = User.find(current_user.id).all_friends

    @mutual_friends = (@friends & @my_friends)

    
  end

  def pendingrequests
    @user=User.find(params[:user_id])
    @pendingrequests=@user.pending_requests
  end

  def receievedrequests
    @user=User.find(params[:user_id])
    @r=@user.received_requests
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<% if @friends %>
<div class="card card-header results-block" id="page-content">
<table class="col-md-12">
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><strong>Name: </strong> <%= friend.full_name %></td>
        <td><strong>Email: </strong> <%= friend.email %></td>
        <td><strong>Actions: </strong> <%= link_to "View Profile", user_path(friend)  ,
                          class: "btn btn-sm btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @all_friends.count > 5 %>
  <%= link_to "View all Results", friend_results_path(@all_friends)  ,
  class: "btn btn-sm btn-success" %>
<% end %>
</div>
<% end %> 

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>' 

app/views/users/friend_results.html.erb
<div class="card card-header results-block" id="page-content">
Render all results here
</div>

app/views/users/friends.html.erb
<div class= "container">
  <% @friends.each do |friend| %>
    <div class: "card " style= "width: 18rem;">
      <%= image_tag friend.avatar_url.to_s, size: "100x100" , class: "card-img-top"  %>
      <div class: "card-body">
        <em class: "card-text"><%=link_to friend.full_name, user_path(friend) %></em>
      </div>
    </div>
  <% end %>
</div>

app/views/users/mutual_friends.html.erb
<div class= "container">
  <% @mutual_friends.each do |friend| %>
    <div class: "card " style= "width: 18rem;">
      <%= image_tag friend.avatar_url.to_s, size: "100x100" , class: "card-img-top"  %>
      <div class: "card-body">
        <em class: "card-text"><%=link_to friend.full_name, user_path(friend) %></em>
      </div>
    </div>
  <% end %>
</div>

app/views/users/myfriends.html.erb
<div class= "container">
  <% @friends.each do |friend| %>
    <div class: "card " style= "width: 18rem;">
      <%= image_tag friend.avatar_url.to_s, size: "100x100" , class: "card-img-top"  %>
      <div class: "card-body">
        <em class: "card-text"><%= friend.full_name %></em>
      </div>
    </div>
  <% end %>
</div>

app/views/users/myprofile.html.erb
<div class= "container">
  
  <h1> Hello </h1>
  <div class: "card " style= "width: 18rem;">
    <%= image_tag @user.avatar_url.to_s, size: "100x100" , class: "card-img-top"  %>
    <div class: "card-body">
      <em class: "card-text"><%= @user.full_name %></em>
    </div>
  </div>

  <h1> All my posts</h1>


  <% @posts.each do |post| %>
    <em>Title:</em><%= post.title %> </br>
    <em>Description:</em><%= post.description %> </br>
  <% end %>
</div>

<div class= container >
  <p> <%= link_to 'friend_request_sent', user_pending_request_path(@user),class: "btn btn-sm btn-success" %> </p>
  
  <p> <%= link_to 'friend_request_recieved', user_receieved_request_path(@user),class: "btn btn-sm btn-success" %></p>
  
  <p><%= link_to 'friends', user_friends_path(@user), class: "btn btn-sm btn-success" %></p>
</div>

app/views/users/pendingrequests.html.erb
<h1>friend request pending</h1>
<%  @pendingrequests.each do |request| %>
  <p><%= request.first_name %> <%= request.last_name %>  
  <%= link_to 'cancel-request', user_friendship_path(current_user,request),method: :delete %>

  </p>
  
<%end%>

app/views/users/receievedrequests.html.erb
<h1>friend request recieved</h1>
<% @r.each do |user| %>
  <p><%= user.first_name %> <%= user.last_name %></p>
  <%= link_to 'accept-request', accept_request_path(user), method: :post%>
  |
  <%= link_to 'Decline', user_friendship_path(user,current_user),method: :delete %>
<%end%>
<br>

app/views/users/show.html.erb
<div class= "container">
  
  <h1> Hello </h1>
  <div class: "card " style= "width: 18rem;">
    <%= image_tag @user.avatar_url.to_s, size: "100x100" , class: "card-img-top"  %>
    <div class: "card-body">
      <em class: "card-text"><%= @user.full_name %></em>
    </div>
  </div>

  <% if(!is_friend(current_user,@user)&&!is_request_sent(current_user,@user)) %>
   <%= button_to 'Add_friend', user_friendships_path(@user), method: :post ,remote:true%>
  <% elsif is_request_sent(current_user,@user) &&!is_friend(current_user,@user)%>
  <%= link_to 'cancel-request', user_friendship_path(current_user,@user),method: :delete %>
  <%else%>
      <%= button_to 'Unfriend', user_unfriend_path(@user), method: :delete ,remote:true%>
  <%end %>
  
  <%= button_to 'Mutual Friends', mutual_friends_path(@user), method: :get %>


  <h1> All my posts</h1>


  <% @posts.each do |post| %>
    <em>Title:</em><%= post.title %> </br>
    <em>Description:</em><%= post.description %> </br>
    <%= link_to 'Show Post',post_path(post) %></br>
  <% end %>
</div>