config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new' 
  end

  root 'welcome#index'

  resources :posts do
    resources :likes
    resources :comments do
      resources :likes
    end
  end

  get 'myprofile', to: 'users#myprofile'

  get 'myfriends', to: 'users#myfriends'

  get 'search_friend', to: 'users#search'

  get 'friend_results', to: 'users#friend_results'

  get 'users/:user_id/friends',to: "users#friends",as: 'user_friends'

  get 'users/:user_id/mutual_friends',to: "users#mutual_friends",as: 'mutual_friends'

  get 'users/:user_id/pendingrequests',to: "users#pendingrequests",as: 'user_pending_request'
  
  get 'users/:user_id/receievedrequests',to: "users#receievedrequests",as: 'user_receieved_request'
  
  post 'users/accept_request/:user_id', to: "friendships#accept",as: 'accept_request'
  
  delete 'users/unfriend/:user_id',to:"friendships#unfriend",as: "user_unfriend"

  resources:users, only: [:show, :destroy] do
    resources:friendships
  end  




  



end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  load_and_authorize_resource except: [:index,:show,:create]
  
  def index
    # @post = Post.all
    
    #show all current user post
    @my_posts = current_user.posts
    @all_posts = @my_posts
    

    #show his friends posts where(post_type: "friends") or (post_type: "everyone")
    @friends = current_user.all_friends
    @friends.each do |friend|
      @all_posts += friend.posts.where(post_type: "friends")
      @all_posts += friend.posts.where(post_type: "public")
    end

    @post = @all_posts

    # byebug

  end

  def new
    @post = Post.new
  end

  def show
    
    # byebug
    @post = Post.find(id = params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def create
    # byebug
    @post = Post.new(params.require(:post).permit(:title,:description))
    post_visibility
    @post.user = current_user
    if @post.save
      flash[:notice] = 'saved successfully'
      redirect_to posts_path
    else
      flash[:error] = 'failed to save'
      redirect_to new_post_path
    end
  end

  def edit
    @post=Post.find(params[:id])
  end

  def update
    # byebug
    @post = Post.find(id= params[:id])
    post_visibility
    if @post.update(params.require(:post).permit(:title,:description))
      flash[:notice] = 'Updated Successfully'
      redirect_to post_path(@post)
    else
      flash[:error] = 'failed to Update'
      redirect_to post_path(@post)
    end

  end

  def destroy
    # byebug
    @post = Post.find(id = params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_visibility
    @type = params[:post_type_id]
    if @type == '1'
      @post.post_type = "public"
    elsif @type == '2'
      @post.post_type = "friends"
    else
      @post.post_type = "only me"
    end
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/edit.html.erb
     
<%= form_for @post, local: true do |f| %>

  <%= f.label :title %>
  
    <%= f.text_field :title, placeholder: "Title of article" %>
  
  </br>
  <%= f.label :description %>
  
    <%= f.text_area :description, placeholder: "Description of article" %>
    </br>
  <%= select_tag(:post_type_id, options_for_select([['Public', 1], ['Friends', 2],['Only me', 3]])) %>
  
<%= f.submit %>

<% end %>

<%= link_to '[ Cancel and return to Posts listing ]', posts_path %>
 

app/views/posts/index.html.erb
<input type="button" class="test" value="test">

  <table >
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Show</th>
      <th>Delete</th>
    </tr>

<% @post.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= link_to 'Show',post_path(post) %></td>
      <% if can? :destroy, post %>
      <td><%= link_to 'Delete',post_path(post), method: :delete  %></td>
      <% end %>
    </tr>
<% end %>
  </table>

<%= link_to "Create New Post" ,new_post_path %> 

app/views/posts/new.html.erb
     
<%= form_for @post, local: true do |f| %>

    <%= f.label :title %>
    
      <%= f.text_field :title, placeholder: "Title of article" %>
    
    </br>
    <%= f.label :description %>
    
      <%= f.text_area :description, placeholder: "Description of article" %>
    </br>
    <%= select_tag(:post_type_id, options_for_select([['Public', 1], ['Friends', 2],['Only me', 3]], 1)) %>
    
  <%= f.submit %>

<% end %>

<%= link_to '[ Cancel and return to Posts listing ]', posts_path %>
   

app/views/posts/show.html.erb
<h1>  Your Post </h1>
<em>Title:</em><%= @post.title %> </br>
<em>Description:</em><%= @post.description %> </br>
<em>By:<%= link_to @post.user.full_name, user_path(@post.user) %></em> 

<% if can? :update, @post %>
|
  <%= link_to 'Edit',edit_post_path(@post), method: :get %>
<% end %>


</br>
<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
</br>
<% if pre_like %>
  <%= link_to 'Unlike', "#{@post.id}/likes/#{pre_like.id}", method: :delete , remote: true %>
<% else %>
  <%= link_to 'Like',post_likes_path(@post), method: :post, remote:true %>
<% end %>

<%= @post.likes.count %>
</br>
------- view all comments here ---------</br>
<% @comments.each do |comment| %>
  <strong>By: <%= comment.user.first_name %></strong> <i><%= comment.com %></i>
  
  <p>
  <% if can? :destroy, comment %>
    <%= link_to 'Delete', "/posts/#{comment.post.id}/comments/#{comment.id}", method: :delete, remote: true %>
  <% end %> 
  <% if can? :update, comment %>
  <%= link_to 'Edit', "/posts/#{comment.post.id}/comments/#{comment.id}/edit", method: :get %>
  <% end %>
  <% pre_like = comment.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= link_to 'Unlike', post_comment_like_path(@post,comment,pre_like), method: :delete , remote: true%>
  <% else %>
    <%= link_to 'Like', post_comment_likes_path(@post,comment), method: :post , remote: true%>
  <% end %>
  
  </p>
  </br>

<% end %>

<div id="add-comment">

</div>
</br>

<%= render 'comments/form' %>