config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new' 
  end

  root 'welcome#index'

  resources :posts do
    resources :likes
    resources :comments do
      resources :likes
    end
  end

  get 'myprofile', to: 'users#myprofile'

  get 'myfriends', to: 'users#myfriends'

  get 'search_friend', to: 'users#search'

  get 'friend_results', to: 'users#friend_results'

  get 'users/:user_id/friends',to: "users#friends",as: 'user_friends'

  get 'users/:user_id/mutual_friends',to: "users#mutual_friends",as: 'mutual_friends'

  get 'users/:user_id/pendingrequests',to: "users#pendingrequests",as: 'user_pending_request'
  
  get 'users/:user_id/receievedrequests',to: "users#receievedrequests",as: 'user_receieved_request'
  
  post 'users/accept_request/:user_id', to: "friendships#accept",as: 'accept_request'
  
  delete 'users/unfriend/:user_id',to:"friendships#unfriend",as: "user_unfriend"

  resources:users, only: [:show, :destroy] do
    resources:friendships
  end  




  



end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
  <small>Copyright &copy; <%= link_to "Google", "https://google.com", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to "Socio Menta", root_path, class: "navbar-brand", id: "logo" %>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       
       <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Friends
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "My friends", user_friends_path(current_user), class: "dropdown-item" %>
            <%= link_to "Pending Requests", user_receieved_request_path(current_user), class: "dropdown-item" %>
            <%= link_to "Requests Sent", user_pending_request_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
       <% end %>
       <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Posts
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Create new Post", new_post_path, class: "dropdown-item" %>
            <%= link_to "View Posts", posts_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
       <% end %>  
       <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile [<%= current_user.full_name %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", myprofile_path, class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Delete profile", '/users', method: :delete ,class: "dropdown-item text-danger", data: { confirm: "Are you sure?" } %> 
            </div>
        </li>
         <li class="nav-item">
           <%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete %>
         </li>
       <% else %>
         <li class="nav-item">
           <%= link_to 'Log in', signin_path, class: "nav-link" %>
         </li>
         <li class="nav-item">
           <%= link_to 'Sign up', signup_path, class: "nav-link" %>
         </li>
       <% end %>
       
     </ul>
     <%= form_tag search_friend_path,class: "form-inline my-2 my-lg-0", remote: true, method: :get do %>
       <%= text_field_tag :friend, params[:friend], placeholder: "Search" , 
       class: "form-control mr-sm-2" %>
       <%= button_tag type: :submit, class: "btn btn-outline-success my-2 my-sm-0" do %>
          Search
        <% end %>
     <% end %>

   </div>
 </nav>

 <div id="friend-results">

 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
  
</html>